# Generated by Django 5.0.1 on 2024-02-20 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_desciption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='complete',
            field=models.CharField(choices=[('Done', 'Done'), ('In Progress', 'In Progress'), ('Not Started', 'Not Started')], max_length=20),
        ),
    ]
