# Generated by Django 5.0.1 on 2024-02-20 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_rename_desciption_task_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Done', 'Done'), ('InProgress', 'In Progress'), ('NotStarted', 'Not Started')], max_length=20),
        ),
    ]
